
package com.dnb.ubo.v3.jsonbeans;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;


/**
 * JSON Schema generated by XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com)
 *
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "transactionInfo",
    "productRequest"
})
public class ApiRequest {

    /**
     * transactionInfo
     * <p>
     *
     * (Required)
     *
     */
    @JsonProperty("transactionInfo")
    private TransactionInfo transactionInfo;
    /**
     * productRequest
     * <p>
     *
     * (Required)
     *
     */
    @JsonProperty("productRequest")
    private ProductRequest productRequest;

    /**
     * transactionInfo
     * <p>
     *
     * (Required)
     *
     * @return
     *     The transactionInfo
     */
    @JsonProperty("transactionInfo")
    public TransactionInfo getTransactionInfo() {
        return transactionInfo;
    }

    /**
     * transactionInfo
     * <p>
     *
     * (Required)
     *
     * @param transactionInfo
     *     The transactionInfo
     */
    @JsonProperty("transactionInfo")
    public void setTransactionInfo(TransactionInfo transactionInfo) {
        this.transactionInfo = transactionInfo;
    }

    /**
     * productRequest
     * <p>
     *
     * (Required)
     *
     * @return
     *     The productRequest
     */
    @JsonProperty("productRequest")
    public ProductRequest getProductRequest() {
        return productRequest;
    }

    /**
     * productRequest
     * <p>
     *
     * (Required)
     *
     * @param productRequest
     *     The productRequest
     */
    @JsonProperty("productRequest")
    public void setProductRequest(ProductRequest productRequest) {
        this.productRequest = productRequest;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder().append(transactionInfo).append(productRequest).toHashCode();
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof ApiRequest) == false) {
            return false;
        }
        ApiRequest rhs = ((ApiRequest) other);
        return new EqualsBuilder().append(transactionInfo, rhs.transactionInfo).append(productRequest, rhs.productRequest).isEquals();
    }

}
